/*
 *  Copyright (c) 2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

package ui

// HTMLTag is a safe, declarative HTML body-element name. Document, executable,
// and embedded-content elements are intentionally excluded.
type HTMLTag string

const (
	HTMLA          HTMLTag = "a"
	HTMLAbbr       HTMLTag = "abbr"
	HTMLAddress    HTMLTag = "address"
	HTMLArea       HTMLTag = "area"
	HTMLArticle    HTMLTag = "article"
	HTMLAside      HTMLTag = "aside"
	HTMLAudio      HTMLTag = "audio"
	HTMLB          HTMLTag = "b"
	HTMLBDI        HTMLTag = "bdi"
	HTMLBDO        HTMLTag = "bdo"
	HTMLBlockquote HTMLTag = "blockquote"
	HTMLBr         HTMLTag = "br"
	HTMLButton     HTMLTag = "button"
	HTMLCanvas     HTMLTag = "canvas"
	HTMLCaption    HTMLTag = "caption"
	HTMLCite       HTMLTag = "cite"
	HTMLCode       HTMLTag = "code"
	HTMLCol        HTMLTag = "col"
	HTMLColgroup   HTMLTag = "colgroup"
	HTMLData       HTMLTag = "data"
	HTMLDatalist   HTMLTag = "datalist"
	HTMLDd         HTMLTag = "dd"
	HTMLDel        HTMLTag = "del"
	HTMLDetails    HTMLTag = "details"
	HTMLDfn        HTMLTag = "dfn"
	HTMLDialog     HTMLTag = "dialog"
	HTMLDiv        HTMLTag = "div"
	HTMLDl         HTMLTag = "dl"
	HTMLDt         HTMLTag = "dt"
	HTMLEm         HTMLTag = "em"
	HTMLFieldset   HTMLTag = "fieldset"
	HTMLFigcaption HTMLTag = "figcaption"
	HTMLFigure     HTMLTag = "figure"
	HTMLFooter     HTMLTag = "footer"
	HTMLForm       HTMLTag = "form"
	HTMLH1         HTMLTag = "h1"
	HTMLH2         HTMLTag = "h2"
	HTMLH3         HTMLTag = "h3"
	HTMLH4         HTMLTag = "h4"
	HTMLH5         HTMLTag = "h5"
	HTMLH6         HTMLTag = "h6"
	HTMLHeader     HTMLTag = "header"
	HTMLHgroup     HTMLTag = "hgroup"
	HTMLHr         HTMLTag = "hr"
	HTMLI          HTMLTag = "i"
	HTMLImg        HTMLTag = "img"
	HTMLInput      HTMLTag = "input"
	HTMLIns        HTMLTag = "ins"
	HTMLKbd        HTMLTag = "kbd"
	HTMLLabel      HTMLTag = "label"
	HTMLLegend     HTMLTag = "legend"
	HTMLLi         HTMLTag = "li"
	HTMLMain       HTMLTag = "main"
	HTMLMap        HTMLTag = "map"
	HTMLMark       HTMLTag = "mark"
	HTMLMenu       HTMLTag = "menu"
	HTMLMeter      HTMLTag = "meter"
	HTMLNav        HTMLTag = "nav"
	HTMLOl         HTMLTag = "ol"
	HTMLOptgroup   HTMLTag = "optgroup"
	HTMLOption     HTMLTag = "option"
	HTMLOutput     HTMLTag = "output"
	HTMLP          HTMLTag = "p"
	HTMLPicture    HTMLTag = "picture"
	HTMLPre        HTMLTag = "pre"
	HTMLProgress   HTMLTag = "progress"
	HTMLQ          HTMLTag = "q"
	HTMLRp         HTMLTag = "rp"
	HTMLRt         HTMLTag = "rt"
	HTMLRuby       HTMLTag = "ruby"
	HTMLS          HTMLTag = "s"
	HTMLSamp       HTMLTag = "samp"
	HTMLSearch     HTMLTag = "search"
	HTMLSection    HTMLTag = "section"
	HTMLSelect     HTMLTag = "select"
	HTMLSmall      HTMLTag = "small"
	HTMLSource     HTMLTag = "source"
	HTMLSpan       HTMLTag = "span"
	HTMLStrong     HTMLTag = "strong"
	HTMLSub        HTMLTag = "sub"
	HTMLSummary    HTMLTag = "summary"
	HTMLSup        HTMLTag = "sup"
	HTMLTable      HTMLTag = "table"
	HTMLTbody      HTMLTag = "tbody"
	HTMLTd         HTMLTag = "td"
	HTMLTextarea   HTMLTag = "textarea"
	HTMLTfoot      HTMLTag = "tfoot"
	HTMLTh         HTMLTag = "th"
	HTMLThead      HTMLTag = "thead"
	HTMLTime       HTMLTag = "time"
	HTMLTr         HTMLTag = "tr"
	HTMLTrack      HTMLTag = "track"
	HTMLU          HTMLTag = "u"
	HTMLUl         HTMLTag = "ul"
	HTMLVar        HTMLTag = "var"
	HTMLVideo      HTMLTag = "video"
	HTMLWbr        HTMLTag = "wbr"
)

// HTML creates a node for a safe HTML body element. The host must register the
// matching React component and explicitly allow its props and events.
func HTML(tag HTMLTag, id string) *NodeBuilder {
	return node(string(tag), id)
}
