// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ui

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCef4e921DecodeGoOsspkgComUi(in *jlexer.Lexer, out *ViewSchema) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "protocolVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProtocolVersion = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "revision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Revision = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "state":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.State = make(map[string]interface{})
				} else {
					out.State = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 interface{}
					if m, ok := v1.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v1.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v1 = in.Interface()
					}
					(out.State)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "sources":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Sources = make(map[string]DataSource)
				} else {
					out.Sources = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 DataSource
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					(out.Sources)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "actions":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Actions = make(map[string]Action)
				} else {
					out.Actions = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 Action
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					(out.Actions)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		case "regions":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Regions).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi(out *jwriter.Writer, in ViewSchema) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"protocolVersion\":"
		out.RawString(prefix[1:])
		out.String(string(in.ProtocolVersion))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	if in.Revision != "" {
		const prefix string = ",\"revision\":"
		out.RawString(prefix)
		out.String(string(in.Revision))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if len(in.State) != 0 {
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.State {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if m, ok := v4Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v4Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v4Value))
				}
			}
			out.RawByte('}')
		}
	}
	if len(in.Sources) != 0 {
		const prefix string = ",\"sources\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Sources {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				(v5Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	if len(in.Actions) != 0 {
		const prefix string = ",\"actions\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v6First := true
			for v6Name, v6Value := range in.Actions {
				if v6First {
					v6First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v6Name))
				out.RawByte(':')
				(v6Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"regions\":"
		out.RawString(prefix)
		(in.Regions).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ViewSchema) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ViewSchema) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ViewSchema) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ViewSchema) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi1(in *jlexer.Lexer, out *UIViewDescriptor) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "route":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Route = string(in.String())
			}
		case "schema":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Schema = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi1(out *jwriter.Writer, in UIViewDescriptor) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Route != "" {
		const prefix string = ",\"route\":"
		out.RawString(prefix)
		out.String(string(in.Route))
	}
	{
		const prefix string = ",\"schema\":"
		out.RawString(prefix)
		out.String(string(in.Schema))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UIViewDescriptor) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UIViewDescriptor) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UIViewDescriptor) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UIViewDescriptor) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi1(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi2(in *jlexer.Lexer, out *Regions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "top-header":
			if in.IsNull() {
				in.Skip()
				out.TopHeader = nil
			} else {
				in.Delim('[')
				if out.TopHeader == nil {
					if !in.IsDelim(']') {
						out.TopHeader = make([]Node, 0, 0)
					} else {
						out.TopHeader = []Node{}
					}
				} else {
					out.TopHeader = (out.TopHeader)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Node
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.TopHeader = append(out.TopHeader, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "left-panel":
			if in.IsNull() {
				in.Skip()
				out.LeftPanel = nil
			} else {
				in.Delim('[')
				if out.LeftPanel == nil {
					if !in.IsDelim(']') {
						out.LeftPanel = make([]Node, 0, 0)
					} else {
						out.LeftPanel = []Node{}
					}
				} else {
					out.LeftPanel = (out.LeftPanel)[:0]
				}
				for !in.IsDelim(']') {
					var v8 Node
					if in.IsNull() {
						in.Skip()
					} else {
						(v8).UnmarshalEasyJSON(in)
					}
					out.LeftPanel = append(out.LeftPanel, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "content":
			if in.IsNull() {
				in.Skip()
				out.Content = nil
			} else {
				in.Delim('[')
				if out.Content == nil {
					if !in.IsDelim(']') {
						out.Content = make([]Node, 0, 0)
					} else {
						out.Content = []Node{}
					}
				} else {
					out.Content = (out.Content)[:0]
				}
				for !in.IsDelim(']') {
					var v9 Node
					if in.IsNull() {
						in.Skip()
					} else {
						(v9).UnmarshalEasyJSON(in)
					}
					out.Content = append(out.Content, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "right-panel":
			if in.IsNull() {
				in.Skip()
				out.RightPanel = nil
			} else {
				in.Delim('[')
				if out.RightPanel == nil {
					if !in.IsDelim(']') {
						out.RightPanel = make([]Node, 0, 0)
					} else {
						out.RightPanel = []Node{}
					}
				} else {
					out.RightPanel = (out.RightPanel)[:0]
				}
				for !in.IsDelim(']') {
					var v10 Node
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.RightPanel = append(out.RightPanel, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "bottom":
			if in.IsNull() {
				in.Skip()
				out.Bottom = nil
			} else {
				in.Delim('[')
				if out.Bottom == nil {
					if !in.IsDelim(']') {
						out.Bottom = make([]Node, 0, 0)
					} else {
						out.Bottom = []Node{}
					}
				} else {
					out.Bottom = (out.Bottom)[:0]
				}
				for !in.IsDelim(']') {
					var v11 Node
					if in.IsNull() {
						in.Skip()
					} else {
						(v11).UnmarshalEasyJSON(in)
					}
					out.Bottom = append(out.Bottom, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi2(out *jwriter.Writer, in Regions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"top-header\":"
		out.RawString(prefix[1:])
		if in.TopHeader == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.TopHeader {
				if v12 > 0 {
					out.RawByte(',')
				}
				(v13).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"left-panel\":"
		out.RawString(prefix)
		if in.LeftPanel == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.LeftPanel {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		if in.Content == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Content {
				if v16 > 0 {
					out.RawByte(',')
				}
				(v17).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"right-panel\":"
		out.RawString(prefix)
		if in.RightPanel == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.RightPanel {
				if v18 > 0 {
					out.RawByte(',')
				}
				(v19).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"bottom\":"
		out.RawString(prefix)
		if in.Bottom == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Bottom {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Regions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Regions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Regions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Regions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi2(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi3(in *jlexer.Lexer, out *PluginManifest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi3(out *jwriter.Writer, in PluginManifest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PluginManifest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PluginManifest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PluginManifest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PluginManifest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi3(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi4(in *jlexer.Lexer, out *Node) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "component":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Component = string(in.String())
			}
		case "layout":
			if in.IsNull() {
				in.Skip()
				out.Layout = nil
			} else {
				if out.Layout == nil {
					out.Layout = new(Layout)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Layout).UnmarshalEasyJSON(in)
				}
			}
		case "props":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Props = make(map[string]Value)
				} else {
					out.Props = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v22 Value
					if in.IsNull() {
						in.Skip()
					} else {
						if data := in.Raw(); in.Ok() {
							in.AddError((v22).UnmarshalJSON(data))
						}
					}
					(out.Props)[key] = v22
					in.WantComma()
				}
				in.Delim('}')
			}
		case "events":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Events = make(map[string]EventHandler)
				} else {
					out.Events = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v23 EventHandler
					if in.IsNull() {
						in.Skip()
					} else {
						(v23).UnmarshalEasyJSON(in)
					}
					(out.Events)[key] = v23
					in.WantComma()
				}
				in.Delim('}')
			}
		case "children":
			if in.IsNull() {
				in.Skip()
				out.Children = nil
			} else {
				in.Delim('[')
				if out.Children == nil {
					if !in.IsDelim(']') {
						out.Children = make([]Node, 0, 0)
					} else {
						out.Children = []Node{}
					}
				} else {
					out.Children = (out.Children)[:0]
				}
				for !in.IsDelim(']') {
					var v24 Node
					if in.IsNull() {
						in.Skip()
					} else {
						(v24).UnmarshalEasyJSON(in)
					}
					out.Children = append(out.Children, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "slots":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Slots = make(map[string][]Node)
				} else {
					out.Slots = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v25 []Node
					if in.IsNull() {
						in.Skip()
						v25 = nil
					} else {
						in.Delim('[')
						if v25 == nil {
							if !in.IsDelim(']') {
								v25 = make([]Node, 0, 0)
							} else {
								v25 = []Node{}
							}
						} else {
							v25 = (v25)[:0]
						}
						for !in.IsDelim(']') {
							var v26 Node
							if in.IsNull() {
								in.Skip()
							} else {
								(v26).UnmarshalEasyJSON(in)
							}
							v25 = append(v25, v26)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Slots)[key] = v25
					in.WantComma()
				}
				in.Delim('}')
			}
		case "when":
			if in.IsNull() {
				in.Skip()
				out.When = nil
			} else {
				if out.When == nil {
					out.When = new(Value)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.When).UnmarshalJSON(data))
					}
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi4(out *jwriter.Writer, in Node) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"component\":"
		out.RawString(prefix)
		out.String(string(in.Component))
	}
	if in.Layout != nil {
		const prefix string = ",\"layout\":"
		out.RawString(prefix)
		(*in.Layout).MarshalEasyJSON(out)
	}
	if len(in.Props) != 0 {
		const prefix string = ",\"props\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v27First := true
			for v27Name, v27Value := range in.Props {
				if v27First {
					v27First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v27Name))
				out.RawByte(':')
				out.Raw((v27Value).MarshalJSON())
			}
			out.RawByte('}')
		}
	}
	if len(in.Events) != 0 {
		const prefix string = ",\"events\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v28First := true
			for v28Name, v28Value := range in.Events {
				if v28First {
					v28First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v28Name))
				out.RawByte(':')
				(v28Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	if len(in.Children) != 0 {
		const prefix string = ",\"children\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v29, v30 := range in.Children {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Slots) != 0 {
		const prefix string = ",\"slots\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v31First := true
			for v31Name, v31Value := range in.Slots {
				if v31First {
					v31First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v31Name))
				out.RawByte(':')
				if v31Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v32, v33 := range v31Value {
						if v32 > 0 {
							out.RawByte(',')
						}
						(v33).MarshalEasyJSON(out)
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	if in.When != nil {
		const prefix string = ",\"when\":"
		out.RawString(prefix)
		out.Raw((*in.When).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Node) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Node) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Node) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Node) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi4(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi5(in *jlexer.Lexer, out *Manifest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "protocolVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProtocolVersion = string(in.String())
			}
		case "plugin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Plugin).UnmarshalEasyJSON(in)
			}
		case "views":
			if in.IsNull() {
				in.Skip()
				out.Views = nil
			} else {
				in.Delim('[')
				if out.Views == nil {
					if !in.IsDelim(']') {
						out.Views = make([]UIViewDescriptor, 0, 1)
					} else {
						out.Views = []UIViewDescriptor{}
					}
				} else {
					out.Views = (out.Views)[:0]
				}
				for !in.IsDelim(']') {
					var v34 UIViewDescriptor
					if in.IsNull() {
						in.Skip()
					} else {
						(v34).UnmarshalEasyJSON(in)
					}
					out.Views = append(out.Views, v34)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "requiredComponents":
			if in.IsNull() {
				in.Skip()
				out.RequiredComponents = nil
			} else {
				in.Delim('[')
				if out.RequiredComponents == nil {
					if !in.IsDelim(']') {
						out.RequiredComponents = make([]string, 0, 4)
					} else {
						out.RequiredComponents = []string{}
					}
				} else {
					out.RequiredComponents = (out.RequiredComponents)[:0]
				}
				for !in.IsDelim(']') {
					var v35 string
					if in.IsNull() {
						in.Skip()
					} else {
						v35 = string(in.String())
					}
					out.RequiredComponents = append(out.RequiredComponents, v35)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi5(out *jwriter.Writer, in Manifest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"protocolVersion\":"
		out.RawString(prefix[1:])
		out.String(string(in.ProtocolVersion))
	}
	{
		const prefix string = ",\"plugin\":"
		out.RawString(prefix)
		(in.Plugin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"views\":"
		out.RawString(prefix)
		if in.Views == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v36, v37 := range in.Views {
				if v36 > 0 {
					out.RawByte(',')
				}
				(v37).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.RequiredComponents) != 0 {
		const prefix string = ",\"requiredComponents\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v38, v39 := range in.RequiredComponents {
				if v38 > 0 {
					out.RawByte(',')
				}
				out.String(string(v39))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Manifest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Manifest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Manifest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Manifest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi5(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi6(in *jlexer.Lexer, out *Layout) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "row":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Row = int(in.Int())
			}
		case "cols":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cols = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi6(out *jwriter.Writer, in Layout) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"row\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Row))
	}
	if in.Cols != 0 {
		const prefix string = ",\"cols\":"
		out.RawString(prefix)
		out.Int(int(in.Cols))
	}
	if in.Offset != 0 {
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Layout) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Layout) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Layout) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Layout) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi6(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi7(in *jlexer.Lexer, out *EventHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "action":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Action = string(in.String())
			}
		case "steps":
			if in.IsNull() {
				in.Skip()
				out.Steps = nil
			} else {
				in.Delim('[')
				if out.Steps == nil {
					if !in.IsDelim(']') {
						out.Steps = make([]ActionStep, 0, 1)
					} else {
						out.Steps = []ActionStep{}
					}
				} else {
					out.Steps = (out.Steps)[:0]
				}
				for !in.IsDelim(']') {
					var v40 ActionStep
					if in.IsNull() {
						in.Skip()
					} else {
						(v40).UnmarshalEasyJSON(in)
					}
					out.Steps = append(out.Steps, v40)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi7(out *jwriter.Writer, in EventHandler) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Action != "" {
		const prefix string = ",\"action\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Action))
	}
	if len(in.Steps) != 0 {
		const prefix string = ",\"steps\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v41, v42 := range in.Steps {
				if v41 > 0 {
					out.RawByte(',')
				}
				(v42).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi7(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi8(in *jlexer.Lexer, out *Effect) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
				out.Value = nil
			} else {
				if out.Value == nil {
					out.Value = new(Value)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.Value).UnmarshalJSON(data))
					}
				}
			}
		case "baseRevision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BaseRevision = string(in.String())
			}
		case "revision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Revision = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "variant":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Variant = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi8(out *jwriter.Writer, in Effect) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Path != "" {
		const prefix string = ",\"path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	if in.Source != "" {
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	if in.Value != nil {
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Raw((*in.Value).MarshalJSON())
	}
	if in.BaseRevision != "" {
		const prefix string = ",\"baseRevision\":"
		out.RawString(prefix)
		out.String(string(in.BaseRevision))
	}
	if in.Revision != "" {
		const prefix string = ",\"revision\":"
		out.RawString(prefix)
		out.String(string(in.Revision))
	}
	if in.To != "" {
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.Variant != "" {
		const prefix string = ",\"variant\":"
		out.RawString(prefix)
		out.String(string(in.Variant))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Effect) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Effect) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Effect) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Effect) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi8(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi9(in *jlexer.Lexer, out *DataSource) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "tool":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tool = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Input = make(map[string]Value)
				} else {
					out.Input = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v43 Value
					if in.IsNull() {
						in.Skip()
					} else {
						if data := in.Raw(); in.Ok() {
							in.AddError((v43).UnmarshalJSON(data))
						}
					}
					(out.Input)[key] = v43
					in.WantComma()
				}
				in.Delim('}')
			}
		case "policy":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Policy = SourcePolicy(in.String())
			}
		case "cache":
			if in.IsNull() {
				in.Skip()
				out.Cache = nil
			} else {
				if out.Cache == nil {
					out.Cache = new(CachePolicy)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Cache).UnmarshalEasyJSON(in)
				}
			}
		case "refreshOn":
			if in.IsNull() {
				in.Skip()
				out.RefreshOn = nil
			} else {
				in.Delim('[')
				if out.RefreshOn == nil {
					if !in.IsDelim(']') {
						out.RefreshOn = make([]string, 0, 4)
					} else {
						out.RefreshOn = []string{}
					}
				} else {
					out.RefreshOn = (out.RefreshOn)[:0]
				}
				for !in.IsDelim(']') {
					var v44 string
					if in.IsNull() {
						in.Skip()
					} else {
						v44 = string(in.String())
					}
					out.RefreshOn = append(out.RefreshOn, v44)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi9(out *jwriter.Writer, in DataSource) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"tool\":"
		out.RawString(prefix)
		out.String(string(in.Tool))
	}
	if len(in.Input) != 0 {
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v45First := true
			for v45Name, v45Value := range in.Input {
				if v45First {
					v45First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v45Name))
				out.RawByte(':')
				out.Raw((v45Value).MarshalJSON())
			}
			out.RawByte('}')
		}
	}
	if in.Policy != "" {
		const prefix string = ",\"policy\":"
		out.RawString(prefix)
		out.String(string(in.Policy))
	}
	if in.Cache != nil {
		const prefix string = ",\"cache\":"
		out.RawString(prefix)
		(*in.Cache).MarshalEasyJSON(out)
	}
	if len(in.RefreshOn) != 0 {
		const prefix string = ",\"refreshOn\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v46, v47 := range in.RefreshOn {
				if v46 > 0 {
					out.RawByte(',')
				}
				out.String(string(v47))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DataSource) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DataSource) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DataSource) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DataSource) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi9(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi10(in *jlexer.Lexer, out *CachePolicy) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ttl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TTL = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi10(out *jwriter.Writer, in CachePolicy) {
	out.RawByte('{')
	first := true
	_ = first
	if in.TTL != 0 {
		const prefix string = ",\"ttl\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.TTL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CachePolicy) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CachePolicy) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CachePolicy) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CachePolicy) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi10(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi11(in *jlexer.Lexer, out *ActionStep) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "action":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Action = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Input = make(map[string]Value)
				} else {
					out.Input = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v48 Value
					if in.IsNull() {
						in.Skip()
					} else {
						if data := in.Raw(); in.Ok() {
							in.AddError((v48).UnmarshalJSON(data))
						}
					}
					(out.Input)[key] = v48
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi11(out *jwriter.Writer, in ActionStep) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Action != "" {
		const prefix string = ",\"action\":"
		out.RawString(prefix)
		out.String(string(in.Action))
	}
	if len(in.Input) != 0 {
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v49First := true
			for v49Name, v49Value := range in.Input {
				if v49First {
					v49First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v49Name))
				out.RawByte(':')
				out.Raw((v49Value).MarshalJSON())
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ActionStep) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ActionStep) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ActionStep) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ActionStep) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi11(l, v)
}
func easyjsonCef4e921DecodeGoOsspkgComUi12(in *jlexer.Lexer, out *Action) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "tool":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tool = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Input = make(map[string]Value)
				} else {
					out.Input = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v50 Value
					if in.IsNull() {
						in.Skip()
					} else {
						if data := in.Raw(); in.Ok() {
							in.AddError((v50).UnmarshalJSON(data))
						}
					}
					(out.Input)[key] = v50
					in.WantComma()
				}
				in.Delim('}')
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
				out.Value = nil
			} else {
				if out.Value == nil {
					out.Value = new(Value)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.Value).UnmarshalJSON(data))
					}
				}
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "variant":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Variant = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "effects":
			if in.IsNull() {
				in.Skip()
				out.Effects = nil
			} else {
				in.Delim('[')
				if out.Effects == nil {
					if !in.IsDelim(']') {
						out.Effects = make([]Effect, 0, 0)
					} else {
						out.Effects = []Effect{}
					}
				} else {
					out.Effects = (out.Effects)[:0]
				}
				for !in.IsDelim(']') {
					var v51 Effect
					if in.IsNull() {
						in.Skip()
					} else {
						(v51).UnmarshalEasyJSON(in)
					}
					out.Effects = append(out.Effects, v51)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGoOsspkgComUi12(out *jwriter.Writer, in Action) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Tool != "" {
		const prefix string = ",\"tool\":"
		out.RawString(prefix)
		out.String(string(in.Tool))
	}
	if len(in.Input) != 0 {
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v52First := true
			for v52Name, v52Value := range in.Input {
				if v52First {
					v52First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v52Name))
				out.RawByte(':')
				out.Raw((v52Value).MarshalJSON())
			}
			out.RawByte('}')
		}
	}
	if in.Path != "" {
		const prefix string = ",\"path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	if in.Value != nil {
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Raw((*in.Value).MarshalJSON())
	}
	if in.Source != "" {
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	if in.To != "" {
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.Variant != "" {
		const prefix string = ",\"variant\":"
		out.RawString(prefix)
		out.String(string(in.Variant))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if len(in.Effects) != 0 {
		const prefix string = ",\"effects\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v53, v54 := range in.Effects {
				if v53 > 0 {
					out.RawByte(',')
				}
				(v54).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Action) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGoOsspkgComUi12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Action) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGoOsspkgComUi12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Action) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGoOsspkgComUi12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Action) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGoOsspkgComUi12(l, v)
}
